from typing import Protocol, List
from scraper.models import RawFetchResult, ProductRecord

class MarketplaceAdapter(Protocol):
    def discover(self, search_url: str) -> List[str]: ...
    def fetch_product(self, url: str) -> RawFetchResult: ...
    def parse(self, raw: RawFetchResult, run_id: str) -> ProductRecord: ...